version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    reviewers:
      - ydah
    assignees:
      - ydah
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
